# -*- coding: utf-8 -*-
"""应用级设计令牌。

v1.1 采用「深海蓝导航 + 雾白工作台 + 翡翠绿强调」的视觉体系。
除本模块外，ui/ 下不应新增颜色字面量，避免不同页面形成第二套主题。
"""
import customtkinter as ctk

# 画布与表面
BG = "#f2f5f9"
SURFACE = "#ffffff"
SURFACE_RAISED = "#f8fafc"
SURFACE_SUNKEN = "#f5f7fa"
SURFACE_HOVER = "#f0f6f5"
SURFACE_DISABLED = "#f3f5f7"

# 侧栏
SIDEBAR = "#10243e"
SIDEBAR_RAISED = "#193451"
SIDEBAR_HOVER = "#1d3b5a"
SIDEBAR_TEXT = "#f7fafc"
SIDEBAR_TEXT_MUTED = "#a9bdd0"

# 边界与文字
BORDER = "#dce4ec"
BORDER_SOFT = "#e7edf3"
BORDER_HOVER = "#86b9ad"
BORDER_DISABLED = "#e5e9ee"
BORDER_BUTTON = "#dbe3eb"
TEXT = "#172438"
TEXT_STRONG = "#0d1726"
TEXT_SECONDARY = "#52657a"
TEXT_MUTED = "#78899a"
TEXT_DISABLED = "#a8b3bf"
TEXT_ON_ACCENT = "#ffffff"

# 品牌色与状态色
ACCENT = "#16836f"
ACCENT_HOVER = "#116c5c"
ACCENT_DARK = "#0f5b50"
ACCENT_SOFT = "#dff3ee"
ACCENT_PALE = "#edf8f5"
SUCCESS = "#37c99a"

BUTTON_SECONDARY_BG = "#f8fafc"
BUTTON_SECONDARY_HOVER = "#edf2f6"
HEADER_BUTTON_HOVER = "#eef4f7"
SCROLLBAR = "#c7d2dd"
SCROLLBAR_HOVER = "#9babb9"

# 字体
FONT_FAMILY = "Microsoft YaHei UI"
FONT_MONO = "Consolas"
BRAND_FONT = (FONT_FAMILY, 19, "bold")
BRAND_MARK_FONT = (FONT_FAMILY, 18, "bold")
NAV_FONT = (FONT_FAMILY, 14)
NAV_FONT_ACTIVE = (FONT_FAMILY, 14, "bold")
HEADER_TITLE_FONT = (FONT_FAMILY, 22, "bold")
HEADER_SUBTITLE_FONT = (FONT_FAMILY, 12)
HEADER_BUTTON_FONT = (FONT_FAMILY, 13)
HERO_KICKER_FONT = (FONT_FAMILY, 12, "bold")
HERO_TITLE_FONT = (FONT_FAMILY, 28, "bold")
HERO_BODY_FONT = (FONT_FAMILY, 14)
SECTION_TITLE_FONT = (FONT_FAMILY, 18, "bold")
SECTION_META_FONT = (FONT_FAMILY, 12)
CARD_TITLE_FONT = (FONT_FAMILY, 15, "bold")
CARD_DESCRIPTION_FONT = (FONT_FAMILY, 12)
CARD_ICON_FONT = (FONT_FAMILY, 16, "bold")
CARD_ACTION_FONT = (FONT_FAMILY, 18)
LOG_TITLE_FONT = (FONT_FAMILY, 12, "bold")
LOG_FONT = (FONT_FAMILY, 12)

DIALOG_TITLE_FONT = (FONT_FAMILY, 20, "bold")
DIALOG_BODY_FONT = (FONT_FAMILY, 16)
DIALOG_BUTTON_FONT = (FONT_FAMILY, 15)
ENTRY_FONT = (FONT_FAMILY, 13)
LABEL_FONT = (FONT_FAMILY, 13)
LABEL_BOLD_FONT = (FONT_FAMILY, 13, "bold")
SMALL_FONT = (FONT_FAMILY, 12)
PREVIEW_FONT = (FONT_MONO, 12)

# 尺寸
WINDOW_GEOMETRY = "1320x860"
WINDOW_MIN_SIZE = (1120, 720)
SIDEBAR_WIDTH = 246
HEADER_HEIGHT = 82
FEATURE_CARD_HEIGHT = 112
CATEGORY_CARD_HEIGHT = 128
DIALOG_BUTTON_HEIGHT = 40
ENTRY_HEIGHT = 36
LOG_AREA_HEIGHT = 158
LOG_COLLAPSED_HEIGHT = 48
LOG_TEXT_HEIGHT = 92


def apply_appearance():
    """在创建任何窗口前应用 CustomTkinter 全局外观。"""
    ctk.set_appearance_mode("light")
    ctk.set_default_color_theme("blue")
